### ISSUE TITLE
One-liner for installing npme

### ISSUE THREAD

**Issue by mmalecki** [npm/npme-installer#18]
At this point we have automated installing every piece of required software besides node and npm. It'd be sweet to have an install script which you can `curl | sh`, just like npm did.

@bcoe pointed to repositories maintained by NodeSource: https://github.com/joyent/node/wiki/installing-node.js-via-package-manager
Those make our job much easier, as we only need to figure out the package manager that's installed.

**Comment by bcoe** [comment]
I think we're where we want to be with this now, by running:

`sudo npm install npme -g --unsafe`

A new box is provisioned, and the npme management tool is installed.
