### ISSUE TITLE
logging stack traces with errors

### ISSUE THREAD

**Issue by timoxley** [npm/npme-installer#21]
There's a number of locations where the logger is told to log `error.message`.

Without a stack trace it's near impossible to figure out the cause of the error, or even where it came from, it's just magically appearing in the log. This is especially painful if the error has bubbled up from elsewhere (e.g. node core) as you can't even grep the app for the message content.

Ideally the logger would accept an error object directly, and be responsible for rendering of the error message and stack trace.

**Comment by bcoe** [comment]
logging has been completely overhauled since this ticket was opened, I think we're in a good place.
