### ISSUE TITLE
support more platforms

### ISSUE THREAD

**Issue by bcoe** [npm/npme-installer#38]
One of the main things that comes up in support are problems that people run into installing on slight variations of our supported platforms, e.g., Ubuntu 14.10 instead of 14.04, or RHEL 6.5 instead of Centos 6.5.

There's a swath of platforms that I thing we 99% support, with a tweak or two to our Ansible scripts, it might be worth testing on a few more platforms.

**Comment by nafisto** [comment]
I was unable to install on the latest version of Amazon Linux (resolved it by switching to Ubuntu Tasty).  Happy to do some testing if it helps.

**Comment by bcoe** [comment]
There's a new installer now that should work on a wider variety of platforms, let's open requests on a platform by platform basis going forward.
