### ISSUE TITLE
Cannot register (login) scope/registry on a client

### ISSUE THREAD

**Issue by evil-shrike** [npm/npme-installer#46]
I'm not sure whatever it's right place to report my issue.

I'm installed npme on Ubuntu 14.04.1 TLS and now trying to associate the registry with my scope on a client.
So on my dev machine I'm running:
```
npm login --registry=http://rnddev05.lab.croc.ru:8080/ --scope=@croc
```
It prompts for credentials. I enter credentials of a user on GitHub.
I hangs for a while and then fails with "Authentication service error".
I can see in /etc/npme/logs/npm-auth-ws.log the following error:
```
REQUEST: {host: 'api.github.com',
  port: 443,
  path: '/authorizations',
  method: 'post',
  headers: 
    { host: 'api.github.com',
      'content-length': 146,
      'content-type': 'application/json; charset=utf-8',
      authorization: 'Base xxx',
      'x-github-otp': undefined,
      'user-agent': 'NodeJS HTTP Client',
      accept: 'application/vnd.github.v3+json' } }
REQUEST BODY: { "scopes":
["user", "public_repo", "repo:status", "gist"], "note": "npm on premises solution (9999999999999), "note_url": "https://www.npmjs.org"}
problem with request: timed out
[Error: 504 Gateway Timeout]
```
It seems like a firewall/proxy problem ("Gateway Timeout"). I do have proxy. It's configured system wide (in Network Settings). But on the server with npme I can access Internet (`curl https://www.npmjs.com` works fine, so do browsers and apt-get).
What can be wrong?
Can it be a chance that npme doesn't use my proxy settings?

**Comment by bcoe** [comment]
Hey @evil-shrike I'm cleaning up some old issues. There's now a new installer that should hopefully solve these issues for you:

`sudo npm install npme -g --unsafe`

Feel free to reopen this ticket if you are continuing to run into problems.
