### ISSUE TITLE
npme install fail

### ISSUE THREAD

**Issue by bshy522** [npm/npme-installer#47]
![image](https://cloud.githubusercontent.com/assets/1124573/5469727/2489b2aa-861a-11e4-8f98-57df7ea5843e.png)

os: centos 6.5
node: 0.10.33
npm: 1.4.28

**Comment by nobleach** [comment]
We're experiencing the same thing. It's obviously permissions related. But we have the user that is performing install listed in our sudoers file as not requiring a password. (We're never asked for a sudo password during install) This completely blocks a working install. Is there a way we could manually perform the post-install steps?

**Comment by bcoe** [comment]
@nobleach unfortunately Ansible requires sudo access to the server for some of the configuration steps, and does not prompt the user for their sudo password. Would it be possible to run the installer with a user that has passwordless sudo, you could then reenable a password after the install.

**Comment by nobleach** [comment]
We did temporarily add `%sudo ALL=(ALL) NOPASSWD: ALL` to our sudoers. But it still threw this error. Could be something CentOS specific (I'm normally a debian/ubunut person) but that seems a bit unlikely. We'll continue to investigate.

**Comment by bcoe** [comment]
Hey @bshy522 there's now a new installer available that should solve these issues for you:

`sudo npm install npme -g --unsafe`

As an added bonus, it introduces a slick new UI:

<img width="841" alt="screen shot 2015-08-31 at 2 20 18 pm" src="https://cloud.githubusercontent.com/assets/194609/9591551/f2cec4b6-4ff0-11e5-9815-71e759cedf6b.png">
