### ISSUE TITLE
On publish 'Error: Maintainer must have an email'

### ISSUE THREAD

**Issue by ekristen** [npm/npme-installer#50]
When publishing some users in my organization get this error and are unable to publish modules. It seems that even though they have a public email address associated with their account that npme still things they don't. 

The exact error is `[Error: Maintainer should have an email: ...`

**Comment by ekristen** [comment]
@bcoe any help would be appreciated.

**Comment by ekristen** [comment]
It seems that "Do no show my email address" on https://github.com/settings/profile prevents publishing from working. Even if on the Emails page you have an email marked as public.

Is there any way we can make it so that email addresses don't have to be public for publish to work?

**Comment by bcoe** [comment]
@ekristen this bug should have been patched, please let me know if you are continuing to have any issues.
