### ISSUE TITLE
Set `npme` user's home directory to `/etc/npme`?

### ISSUE THREAD

**Issue by mmalecki** [npm/npme-installer#59]
Right now we create a `/home/npme` which is kinda useless. We could set `npme` user's home directory to `/etc/npme` so that when people run `su - npme` they're dropped in there instead of the empty `/home/npme`.

**Comment by bcoe** [comment]
If we can get people using the new containerized installer this shouldn't be an issue any longer, we simply mount a couple folders on the enclosing host.
