### ISSUE TITLE
Installing on Debian

### ISSUE THREAD

**Issue by gustavnikolaj** [npm/npme-installer#69]
We're running Debian Wheezy, which is using initd and not upstart. I ran into some trouble and had to patch some code in the ndm module to make it run. In the file `/etc/npme/node_modules/ndm/lib/config.js` I had to hardcode `this.platform = 'initd';` towards the end of the constructor function. https://github.com/npm/ndm/blob/master/lib/config.js#L43

If I didn't do that, the part of the `lib/service.js` file in ndm that finds the platform api would look for a platform api named `linux` and not find anything, and default back to ubuntu, which is upstart based. https://github.com/npm/ndm/blob/master/lib/service.js#L61

The problem seems to be that calling `npme generate-scripts` calls the command `ndm generate` without passing on environment variables or the platform parameter. https://github.com/npm/npme-installer/blob/master/bin/npme.js#L152

Both of the following examples would result in upstart-scripts being generated:

```
$ NDM_PLATFORM=initd npme generate-scripts
$ npme --platform=initd generate-scripts
```

I think that this problem might be the same as https://github.com/npm/ndm/issues/100 - but I'm honestly not sure.

I looked around the code for a way to patch it in a better way, so that I could submit a PR. But I couldn't find any obvious way, so I'll not make an attempt.

I had to compile a newer version of couchdb, but other than that, it worked fine after I fixed the above. A little note about the versions required of the different dependencies would have been helpful in the documentation. I had to dig around a little, but I eventually found the information on [this page](https://github.com/npm/npm-registry-couchapp).

**Comment by gustavnikolaj** [comment]
When running `NDM_PLATFORM=initd npme restart` ndm picks up on the platform change, so passing on the environment variables work in some cases. restart is calling ndm in the same way as the generate-scripts command.

I would have expected that adding `"--platform": "initd"` to the `args` object in /etc/npme/service.json would have been enough, but that doesn't seem to have any effect.

**Comment by bcoe** [comment]
Hey @gustavnikolaj, could you give our new installer a shot?

`sudo npm install npme -g --unsafe`

Added bonus, there's now a slick UI:

<img width="841" alt="screen shot 2015-08-31 at 2 20 18 pm" src="https://cloud.githubusercontent.com/assets/194609/9590675/062cb2bc-4feb-11e5-89cc-83d3cfc5a4c3.png">

Again, cleaning up issues; feel free to reopen this.

**Comment by gustavnikolaj** [comment]
Hey @bcoe. I would love to, if you could point me to documentation or tell me a little about how I make sure that the current contents of the registry will still persist after a new installation is done.

**Comment by bcoe** [comment]
@gustavnikolaj sure thing, in your current registry there are three files and folders that you should backup:

* `/etc/npme/whitellist`: this file contains all of the packages you have currently whitelisted from the global npm registry.
* `/etc/npme/couchdb`: this folder contains your current CouchDB database files.
* `/etc/npme/packages`: this folder contains the binaries for all the packages that you have published.

If you backup these files, you should be able to run the new installer:

https://gist.github.com/bcoe/5d3efe3e4a518789a7bb

And, once everything is up and running, plop these files into the appropriate location. Before doing so, you'll stop npmE from the new admin console then you'll place the files in the appropriate location:

`/etc/npme/couchdb` -> `/usr/local/lib/npme/couchdb`
`/etc/npme/packages` -> `/usr/local/lib/npme/packages`
`/etc/npme/whitelist` -> `/usr/local/lib/npme/data/whitelist`

Let me know if you run into any issues -- going forward you should be able to simply backup `/usr/local/lib/npme`.
