### ISSUE TITLE
policy-follower process not coming back up after a periodic restart

### ISSUE THREAD

**Issue by gustavnikolaj** [npm/npme-installer#70]
@ping bcoe

I could not find this code on github, so I assume it's a private repository, hence why I'm writing it here, and pinging the author.

Our systems monitoring team noticed that the policy-follower process left a .pid file in /var/run even after it was exited. I started looking into it. It turns out that it runs for a while after you do a `npme restart` but then after a while it restarts, and is unable to bring it back up again. The last entry in the log /etc/npme/logs/policy-follower.log is:

```
performing periodic restart of policy follower
```

Seems to stem from this code in policy-follower/lib/follower.js line 40 (at version 0.0.15).

```js
setInterval(function() {
    _this.logger.info('performing periodic restart of policy follower');
    process.exit(0);
  }, this.restartMS);
```

I am running with mostly default settings, except from having `"--read-through-cache"` enabled in the args section of service.json.

I'm running the service on debian, and this could possibly be tied to #69 as the problem there seemed to be that parts of the code had a hard time figuring out that it was initd and not upstart. I guess the same could explain this.

I was not able to find the code responsible for keeping the process running. If I can be of any assistance, I'll be happy to help as best I can debugging this issue.

**Comment by bcoe** [comment]
@gustavnikolaj I haven't actually tested npmE on debian, I find it interesting that a pid file gets dropped down. Do you know if you're running the services with initd or upstart?

**Comment by bcoe** [comment]
The problem would be originating in this initd script I believe:

https://github.com/npm/ndm/blob/master/templates/init-d.ejs

does anything jump out at you?

**Comment by gustavnikolaj** [comment]
The init.d script works as expected. 

The problem is that the code in the module policy-follower is killing itself periodically and that there is nothing on an init.d system that keeps the process running, like for example the `Restart=always` option in systemd or `respawn` in upstart.

The pidfiles are left dangling, as the init.d script is responsible for the cleanup, but is never triggered, due to the process terminating itself.

Assuming that you rely on upstarts `respawn` to keep the process running and I'm not overlooking anything, this is "working as intended".

For now I have disabled the policy-follower service, and it is still working fine, as long as I don't need the mirror functionality.

**Comment by gustavnikolaj** [comment]
https://www.npmjs.com/package/forever could be used to keep these services running, as a simple and elegant solution for the lack of a similar functionality in init.d.

**Comment by gustavnikolaj** [comment]
There's another option, [runit](http://smarden.org/runit).

**Comment by bcoe** [comment]
Hey @gustavnikolaj if you run the newest version of the npmE installer (which is now itself Docker based) we simply have a cron job setup that ensures services are up and running periodically by running:

`npme start`

This operation is a noop, so on initd based systems it's a reasonable replacement for the restart functionality we were leaning on upstart for ... perhaps you can setup something similar?

I'd also encourage you to try out our new off-the-shelf containerized installer:

`sudo npm install npme -g --unsafe`

Just doing a bit of an issue cleanup, feel free to reopen this ticket if this doesn't do the trick for you.
